name: Daily Stock Bot

on:
  schedule:
    - cron: '55 0,1,2,3,4 * * 1-5'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - name: 下載程式碼
      uses: actions/checkout@v3
      
    - name: 安裝 Python 環境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: 安裝看盤與畫圖套件
      # 🌟 這裡多加了 matplotlib 這個畫圖神器
      run: pip install yfinance pandas requests matplotlib
        
    - name: 執行股票小秘書
      env:
        LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }} # 🌟 把圖床鑰匙交給程式
      run: python stock_bot.py
      
